# Generated by Django 4.0.3 on 2022-03-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_person_name'),
        ('contacts', '0002_alter_person_slug'),
    ]

    operations = [
    ]
