# Generated by Django 4.0.3 on 2022-03-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_merge_0002_alter_person_name_0002_alter_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
