# Generated by Django 4.0.3 on 2022-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
