# Generated by Django 4.0.3 on 2022-03-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_deletedcontacts'),
        ('contacts', '0005_person_qr_code'),
    ]

    operations = [
    ]
