# Generated by Django 4.0.3 on 2022-03-16 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0006_merge_0005_deletedcontacts_0005_person_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedcontacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
